# 15. Teste desenvolvido por Jonathan Silveira - Instagram: @jonathandev01
x = int(input('\nInsira o valor em dinheiro: '))
print('A quantidade de notas de R$ 100,00 é: ', x / 100)
print('A quantidade de notas de R$ 50,00 é: ', x / 50)
print('A quantidade de notas de R$ 20,00 é: ', x / 20)
print('A quantidade de notas de R$ 10,00 é: ', x / 10)
print('A quantidade de notas de R$ 5,00 é: ', x / 5)
print('A quantidade de notas de R$ 2,00 é: ', x / 2)
print('A quantidade de moedas de R$ 0,50 é: ', x / 0.5)
print('A quantidade de moedas de R$ 0,25 é: ', x / 0.25)
print('A quantidade de moedas de R$ 0,10 é: ', x / 0.10)
print('A quantidade de moedas de R$ 0,05 é: ', x / 0.05)