a = float(input('\nValor R$ '))
b = float(input('Porcentagem % '))
c = (b * a / 100)
valor_real1 = '\033[0;34mR$ {:,.2f}\033[m'.format(a).replace(",", "X").replace(".", ",").replace("X", ".")
valor_real2 = '\033[0;35mR$ {:,.2f}\033[m'.format(c).replace(",", "X").replace(".", ",").replace("X", ".")
print(f'\n\033[0;31m{b:.1f}%\033[m de {valor_real1} = {valor_real2}\n')