# 41. Retirar quebra de linha.
# Desenvolvido por Jonathan Silveira - Instagram: @ jonathandev01

print ('J')
print ('O')
print ('N')
print ('A')
print ('T')
print ('H')
print ('A')
print ('N')
print ('D')
print ('E')
print ('V')
print ('E')
print ('L')
print ('O')
print ('P')
print ('E')
print ('R')